---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5e67563d688f7500194fddcf/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Global Site Config
  templates:
  - config
- type: document
  path: _data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: _data/author.json
  label: Author
  templates:
  - author
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: document
  path: contact.md
  label: Contact
  templates:
  - contact
- type: directory
  path: ''
  label: Page
  create: all
  match: "**/*.md"
  exclude: "{_posts/**,README.md,LICENSE.md,index.md,contact.md}"
  templates:
  - page
- type: jekyll-posts
  label: Post
  create: all
  templates:
  - post
- type: document
  path: _data/subscribe.json
  label: Subscribe
  templates:
  - subscribe
- type: document
  path: _data/menus.yml
  label: Site Menus
  templates:
  - site_menus
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
